# Generated by Django 5.2.1 on 2025-07-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_coupon_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotel.hotel'),
        ),
    ]
