# Generated by Django 5.2.1 on 2025-07-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotelgallery_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
