# Generated by Django 5.2.1 on 2025-07-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotelgallery_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facebook',
            field=models.URLField(default='https://facebook.com', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram',
            field=models.URLField(default='https://facebook.com', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter',
            field=models.URLField(default='https://facebook.com', max_length=100),
        ),
    ]
