# Generated by Django 5.2.1 on 2025-07-24 20:59

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_facebook_hotel_instagram_hotel_twitter'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
