# Generated by Django 5.2.1 on 2025-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_hotel_tags_hotel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='room.jpg', upload_to='Room'),
        ),
    ]
