# Generated by Django 5.2.1 on 2025-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default='room.jpg', upload_to='Room'),
        ),
    ]
