# Generated by Django 5.2.1 on 2025-07-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_room_image_roomtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(upload_to='Room'),
        ),
    ]
