# Generated by Django 5.2.1 on 2025-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_roomtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_type'),
        ),
    ]
