# Generated by Django 5.2.1 on 2025-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_roomtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
