# Generated by Django 5.2.1 on 2025-07-25 14:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_roomtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
