# Generated by Django 5.2.1 on 2025-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
