# Generated by Django 5.2.1 on 2025-08-05 15:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_booking_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abxchdjkiryteqolp', blank=True, length=10, max_length=20, null=True, prefix='', unique=True),
        ),
    ]
